spring.application.name=ai-integrated-chatbot

ai.api.base-url=${AI_API_BASE_URL:http://localhost:1234/v1}
ai.api.model-name=${AI_API_MODEL_NAME:meta-llama-3.1-8b-instruct}

resilience4j.circuitbreaker.instances.aiCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.aiCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.aiCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.aiCircuitBreaker.wait-duration-in-open-state=10s

resilience4j.retry.instances.aiRetry.max-attempts=3
resilience4j.retry.instances.aiRetry.wait-duration=2s
resilience4j.retry.instances.aiRetry.enable-exponential-backoff=true
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
resilience4j.retry.retryAspectOrder=2
logging.level.io.github.resilience4j=DEBUG
